apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-fiber-deployment
spec:
  selector:
    matchLabels:
      app: golang-fiber
  template:
    metadata:
      labels:
        app: golang-fiber
    spec:
      containers:
      - name: golang-fiber
        image: gcr.io/google-containers/busybox
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

