apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-fiber-deployment-v1.2
spec:
  selector:
    matchLabels:
      app: golang-fiber
  template:
    metadata:
      labels:
        app: golang-fiber
    spec:
      containers:
      - name: golang-fiber
        image: derryrenaldy/golang-fiber:v1.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: golang-fiber-service2
spec:
  type: LoadBalancer
  selector:
    app: golang-fiber
  ports:
  - port: 3000
    targetPort: 3000
