apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-fiber-deployment-v1.4
spec:
  selector:
    matchLabels:
      app: golang-fiber
  template:
    metadata:
      labels:
        app: golang-fiber
    spec:
      containers:
      - name: golang-fiber
        image: derryrenaldy/golang-fiber:v1.9
        ports:
        - containerPort: 3000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: golang-fiber-service
spec:
  type: LoadBalancer
  selector:
    app: golang-fiber
  ports:
  - port: 3000
    targetPort: 3000
    name: http
    protocol: TCP
